ALTER TABLE pacientes
    ADD COLUMN habitacion VARCHAR(5) NOT NULL UNIQUE,
    ADD COLUMN fechaSalida TIMESTAMP,
    ADD COLUMN estado BOOLEAN DEFAULT TRUE,
    ADD COLUMN observaciones VARCHAR(200) DEFAULT 'SIN OBSERVACIONES';
